Traceback (most recent call last):
  File "C:\Users\Huawei\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection_cext.py", line 565, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Cannot add or update a child row: a foreign key constraint fails (`ktp_monitor`.`pupils_info`, CONSTRAINT `pupils_info_ibfk_1` FOREIGN KEY (`div_id`) REFERENCES `div_info` (`div_id`))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Huawei\Desktop\3_year\tppo_db\add_new_pupil\test_add_new_pupil.py", line 16, in <module>
    add_new_pupil(pupil)
  File "C:\Users\Huawei\Desktop\3_year\tppo_db\add_new_pupil\add_new_pupil.py", line 25, in add_new_pupil
    mycursor.execute(add_pupil_query)
  File "C:\Users\Huawei\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor_cext.py", line 279, in execute
    result = self._cnx.cmd_query(
  File "C:\Users\Huawei\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection_cext.py", line 573, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`ktp_monitor`.`pupils_info`, CONSTRAINT `pupils_info_ibfk_1` FOREIGN KEY (`div_id`) REFERENCES `div_info` (`div_id`))
